Repository Opetushallitus/koto-rekisteri, pull requests merged in 2025-02, with the labels that each got.

#667 feat: add opentelemetry support (but no instrumentation yet)
  .github/renovate.json
  docker-compose.yml
  infra/lib/service-stack.ts
  otel-config.yml
  server/pom.xml
  server/src/main/resources/application-prod.properties
  server/src/main/resources/application-qa.properties
  server/src/main/resources/application-untuva.properties
  server/src/main/resources/application.properties
  server/src/test/resources/application.properties
Labels: enhancement, devex

#742 feat: log data protection audits to cloudwatch
  infra/lib/log-groups-stack.ts
Labels: enhancement

#794 fix: disable otel logs
  server/src/main/resources/application.properties
Labels: bug, o11y

#792 feat: enable container insights in production
  infra/lib/environment-stage.ts
  infra/lib/service-stack.ts
Labels: enhancement, o11y

#814 chore(deps): update otel semconv to 1.30.0
  server/pom.xml
Labels: dependencies

#816 feat: separate slack alarms channels
  infra/lib/accounts.ts
  infra/lib/environment-stage.ts
Labels: o11y

#799 feat(scripts): run otel collector when starting tmux sess
  scripts/start_otel_collector.sh
  scripts/start_tmux.sh
Labels: enhancement, devex

#846 fix: netplex JSON vulnerability in test code
  server/pom.xml
Labels: security

#845 Add Slack notification to GHA workflows
  .github/workflows/slack-notifier.yml
Labels: ci, devex
